# app.yaml (Git Repo에 저장)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
spec:
  selector:
    matchLabels:
      app: gitops-demo-app
  replicas: 5 # 파드 2개로 시작
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: demo-container
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-service
spec:
  selector:
    app: gitops-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # GCP LoadBalancer를 생성하여 외부에 노출